global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 2s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'remotepushgateway'
    scrape_interval: 20s
    honor_labels: true
    static_configs:
      - targets: ['https://bx9ufxvqfe.eu-west-2.awsapprunner.com']

  - job_name: 'jacoco_coverage'
    honor_labels: true
    static_configs:
      - targets: [ 'pushgateway:9091' ]
